### ISSUE TITLE
Transfer to engineers.sg

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#298]
## Objectives

1. Smooth transfer / mapping / redirection of URLs to `engineers.sg`
    - events api `webuild.sg/api/v1/events
    - main website `webuild.sg`
    - calendar url `webuild.sg/cal`
1. Archival of relevant sites
    - `data.webuild.sg`
    - `live.webuild.sg`
1. Deprecation of unused sites / URLs
    - repository api
    - repository list

## Todo

- [x] Archive `data.webuild.sg` to GitHub pages `webuildsg.github.io/data`
    - Access https://webuildsg.github.io/data/
    - Refer to code commit https://github.com/webuildsg/data/commit/33aaee4073a930254defa25c124b9c16d2abb141
    - Redirect `data.webuild.sg` to `webuildsg.github.io/data` in CloudFlare
       ![image](https://user-images.githubusercontent.com/413879/44440208-b6f8d280-a5f9-11e8-8bd1-9e01d7cb23e1.png)
- [x] Archive `live.webuild.sg` to GitHub pages `webuildsg.github.io/live`
    - Access https://webuildsg.github.io/live/
    - Refer to code commit https://github.com/webuildsg/live/commit/c2d7326eafe56a0f8777a5d496cfe9f4a5c6473d
    - Redirect in CloudFlare 
![image](https://user-images.githubusercontent.com/413879/44440191-ad6f6a80-a5f9-11e8-9355-9831bee5ef36.png)
- [x] Create a re-direction note on `webuild.sg` hosted on GitHub pages
    - Code commit in `redirect` branch https://github.com/webuildsg/webuild/tree/redirect
        ![image](https://user-images.githubusercontent.com/413879/44441178-f32e3200-a5fd-11e8-9ea4-3a38e587445d.png)
- [x] Redirect `webuild.sg/api/v1/event` to `engineers.sg/api/events`
    - CloudFlare page rules 
        ![image](https://user-images.githubusercontent.com/413879/44441602-fde9c680-a5ff-11e8-8a70-a3fcd7c24d8f.png)
- [x] Redirect `webuild.sg/cal` to `engineers.sg/cal` after https://github.com/engineersftw/website/issues/31
    - ![image](https://user-images.githubusercontent.com/413879/44442259-9b92c500-a603-11e8-9d2b-1c6af0ea2b5e.png)
- [x] Complete `engineers.sg` tasks https://github.com/engineersftw/website/issues/34
- [x] Redirect `webuild.sg` to `engineers.sg/events`
    ![image](https://user-images.githubusercontent.com/413879/44447791-d7398900-a61b-11e8-9567-bf947be9ab34.png)
    ![image](https://user-images.githubusercontent.com/413879/44447878-30a1b800-a61c-11e8-9f76-9b9947beb3fe.png)
- [x] Redirect `assets.webuild.sg` to `webuildsg.github.io/assets`
- [x] Add a link to the archives https://web.archive.org/web/*/http://webuild.sg/
- [x] Take a last snapshot of the `webuild.sg`

**Comment by sayanee** [comment]
## Additional Todo:

- [ ] Redirect `webuild.sg` to `engineers.sg/events`
- [ ] Redirect `assets.webuild.sg` to `webuildsg.github.sg/assets`

**Comment by sayanee** [comment]
Last snapshot of `webuild.sg` full page

![webuild](https://user-images.githubusercontent.com/413879/44447345-4a420000-a61a-11e8-955e-d72048a041c8.png)

**Comment by sayanee** [comment]
🎉 ❤️ Thanks @miccheng @cheeaun @alyssaq @sebdeckers 💋 and many many others 🙇🏻‍♀️!

**Comment by miccheng** [comment]
Thanks @sayanee for your trust in us.

**Comment by harishpillay** [comment]
Good job all.

**Comment by jedimdan** [comment]
What a journey, @sayanee @notthetup!
